@extends('adminlte::page')
@section('title','Mi perfil')
@section('content_header')<h1><i class="fas fa-user-circle mr-2"></i>Mi perfil</h1>@stop
@section('content')
<div class="row">
 <div class="col-lg-4"><div class="card profile-card text-center"><div class="card-body py-5">
 @if($user->profile_photo_path)<img id="photo-preview" src="{{ route('profile.account.photo.show', ['v' => $user->updated_at?->timestamp]) }}" class="profile-photo mx-auto mb-3" alt="Foto de perfil">@else<div id="profile-initial" class="profile-avatar mx-auto mb-3">{{ strtoupper(substr($user->person?->full_name ?? $user->username,0,1)) }}</div><img id="photo-preview" class="profile-photo mx-auto mb-3 d-none" alt="Vista previa">@endif
 <h4>{{ $user->person?->full_name ?? 'Usuario OCSA' }}</h4><p class="text-muted">{{ $user->username }}</p><span class="badge badge-{{ $user->is_system_owner?'primary':'secondary' }}">{{ $user->is_system_owner?'Dueño del sistema':'Usuario' }}</span>
 <form method="POST" action="{{route('profile.account.photo')}}" enctype="multipart/form-data" class="mt-4">@csrf<input id="photo-input" type="file" name="photo" accept="image/jpeg,image/png,image/webp" class="form-control-file @error('photo') is-invalid @enderror"><small class="text-muted d-block mt-2">JPG, PNG o WebP. Máximo 2 MB.</small>@error('photo')<small class="text-danger">{{$message}}</small>@enderror<button class="btn btn-outline-primary btn-sm mt-3"><i class="fas fa-camera mr-1"></i>Cambiar foto</button></form>
 @if(session('photo_status'))<div class="alert alert-success mt-3 mb-0">{{session('photo_status')}}</div>@endif
 </div></div></div>
 <div class="col-lg-8">
  <div class="card card-outline card-primary"><div class="card-header"><h3 class="card-title">Datos de acceso</h3></div><form method="POST" action="{{ route('profile.account.update') }}"><div class="card-body">@csrf @method('PUT') @if(session('profile_status'))<div class="alert alert-success">{{session('profile_status')}}</div>@endif<label>Correo / usuario</label><input type="email" name="username" value="{{old('username',$user->username)}}" class="form-control @error('username') is-invalid @enderror">@error('username')<div class="invalid-feedback">{{$message}}</div>@enderror</div><div class="card-footer text-right"><button class="btn btn-primary">Guardar datos</button></div></form></div>
  <div class="card card-outline card-warning"><div class="card-header"><h3 class="card-title">Cambiar contraseña</h3></div><form method="POST" action="{{ route('profile.account.password') }}"><div class="card-body">@csrf @method('PUT') @if(session('password_status'))<div class="alert alert-success">{{session('password_status')}}</div>@endif
  <div class="form-group"><label>Contraseña actual</label><div class="input-group"><input id="current-password" type="password" name="current_password" class="form-control @error('current_password') is-invalid @enderror"><div class="input-group-append"><button type="button" class="btn btn-outline-secondary toggle-password" data-target="#current-password"><i class="fas fa-eye"></i></button></div>@error('current_password')<div class="invalid-feedback">{{$message}}</div>@enderror</div></div>
  <div class="row"><div class="col-md-6"><label>Nueva contraseña</label><div class="input-group"><input id="new-password" type="password" name="password" class="form-control @error('password') is-invalid @enderror"><div class="input-group-append"><button type="button" class="btn btn-outline-secondary toggle-password" data-target="#new-password"><i class="fas fa-eye"></i></button></div></div></div><div class="col-md-6"><label>Confirmar contraseña</label><div class="input-group"><input id="confirm-password" type="password" name="password_confirmation" class="form-control"><div class="input-group-append"><button type="button" class="btn btn-outline-secondary toggle-password" data-target="#confirm-password"><i class="fas fa-eye"></i></button></div></div></div></div>@error('password')<small class="text-danger">{{$message}}</small>@enderror</div><div class="card-footer text-right"><button class="btn btn-warning">Actualizar contraseña</button></div></form></div>
 </div>
</div>
@stop
@section('css')<style>.profile-card{border:0;background:linear-gradient(145deg,#fff,#eef5ff)}.profile-avatar,.profile-photo{width:110px;height:110px;border-radius:28px;object-fit:cover;box-shadow:0 12px 30px rgba(18,102,241,.25)}.profile-avatar{background:linear-gradient(135deg,#1266f1,#00b4d8);display:grid;place-items:center;color:#fff;font-size:38px;font-weight:700}</style>@stop
@section('js')<script>$('.toggle-password').on('click',function(){const input=$($(this).data('target'));const show=input.attr('type')==='password';input.attr('type',show?'text':'password');$(this).find('i').toggleClass('fa-eye fa-eye-slash');});$('#photo-input').on('change',function(){const file=this.files[0];if(!file)return;$('#profile-initial').addClass('d-none');$('#photo-preview').attr('src',URL.createObjectURL(file)).removeClass('d-none');});</script>@stop
