@extends('adminlte::page')
@section('title','Monitor de integración')
@section('content_header')
<div class="d-flex justify-content-between align-items-center"><div><h1>Monitor de integración</h1><p class="text-muted mb-0">Evidencia de consultas OCSA, envíos y respuestas de Osinergmin.</p></div><span class="badge badge-{{ $environment==='production'?'success':'warning' }} p-2">{{ strtoupper($environment) }}</span></div>
@stop
@section('content')
@if(session('status'))<div class="alert alert-success">{{session('status')}}</div>@endif
@if(session('warning'))<div class="alert alert-warning">{{session('warning')}}</div>@endif
@can('integration.monitor.execute')
<div class="card card-outline card-primary"><div class="card-body d-flex flex-wrap justify-content-between align-items-center"><div><h5 class="mb-1">Ejecución manual controlada</h5><p class="text-muted mb-0">Disponible para usuarios autorizados. El resultado quedará en esta bitácora.</p></div><form method="POST" action="{{route('integration-monitor.send-now')}}" class="form-inline" onsubmit="return confirm('¿Iniciar una retransmisión manual ahora?')">@csrf<select name="environment" class="form-control mr-2"><option value="development">Demo / certificación</option><option value="production" @selected($environment==='production')>Producción</option></select><button class="btn btn-primary"><i class="fas fa-play mr-1"></i>Ejecutar ahora</button></form></div></div>
@endcan
<div class="card card-outline card-info"><div class="card-body"><h5>Enlace externo de solo lectura</h5><p class="text-muted">Válido durante 24 horas. No ejecuta envíos ni expone coordenadas, tokens o nombres de clientes.</p><div class="input-group"><input id="public-status-url" value="{{$publicStatusUrl}}" class="form-control" readonly><div class="input-group-append"><button type="button" class="btn btn-info" onclick="navigator.clipboard.writeText(document.getElementById('public-status-url').value)"><i class="fas fa-copy mr-1"></i>Copiar</button><a href="{{$publicStatusUrl}}" target="_blank" class="btn btn-outline-info">Abrir</a></div></div></div></div>
@if($cronStale)<div class="alert alert-danger"><i class="fas fa-exclamation-triangle mr-1"></i><b>El cron no presenta actividad reciente.</b> No existe una ejecución registrada en los últimos 5 minutos.</div>@else<div class="alert alert-success"><i class="fas fa-check-circle mr-1"></i>El cron presenta actividad reciente.</div>@endif
<div class="row">
 <div class="col-md-4"><div class="info-box shadow-sm"><span class="info-box-icon bg-info"><i class="fas fa-clock"></i></span><div class="info-box-content"><span class="info-box-text">Última actividad</span><span class="info-box-number">{{$latestRun?->created_at?->format('d/m/Y H:i:s') ?? 'Nunca'}}</span><small>{{$latestRun?->message}}</small></div></div></div>
 <div class="col-md-4"><div class="info-box shadow-sm"><span class="info-box-icon bg-success"><i class="fas fa-check"></i></span><div class="info-box-content"><span class="info-box-text">Última ejecución exitosa</span><span class="info-box-number">{{$lastSuccess?->created_at?->format('d/m/Y H:i:s') ?? 'Ninguna'}}</span></div></div></div>
 <div class="col-md-4"><div class="info-box shadow-sm"><span class="info-box-icon bg-warning"><i class="fas fa-flask"></i></span><div class="info-box-content"><span class="info-box-text">Datos demo</span><span class="info-box-number">{{$demoClients}} clientes / {{$demoRecords}} tramas</span></div></div></div>
</div>
<div class="card card-outline card-danger"><div class="card-header"><h3 class="card-title">Errores por ejecución</h3></div><div class="card-body p-0"><div class="table-responsive"><table class="table table-sm table-hover mb-0"><thead><tr><th>Fecha</th><th>Etapa</th><th>Cliente</th><th>HTTP</th><th>Detalle</th></tr></thead><tbody>@forelse($recentErrors as $error)<tr><td class="text-nowrap">{{$error->created_at->format('d/m/Y H:i:s')}}</td><td><span class="badge badge-danger">{{$error->stage}}</span></td><td>{{$error->person?->full_name ?? 'Sistema'}}</td><td>{{$error->http_status ?? '-'}}</td><td>{{$error->safe_message}} @if($error->safe_context)<details class="mt-1"><summary class="text-primary" style="cursor:pointer">Ver respuesta técnica</summary><pre class="small bg-light p-2 mt-1 mb-0" style="white-space:pre-wrap">{{json_encode($error->safe_context, JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)}}</pre></details>@endif</td></tr>@empty<tr><td colspan="5" class="text-center py-4 text-muted">No hay errores registrados.</td></tr>@endforelse</tbody></table></div></div><div class="card-footer">{{$recentErrors->links()}}</div></div>
<div class="card card-outline card-warning"><div class="card-header"><h3 class="card-title">Motivos de rechazo por unidad</h3></div><div class="card-body p-0"><div class="table-responsive"><table class="table table-sm table-hover mb-0"><thead><tr><th>Fecha</th><th>Placa</th><th>Cliente</th><th>Motivo informado</th><th>Sugerencia</th></tr></thead><tbody>@forelse($recentRejections as $item)<tr><td class="text-nowrap">{{$item->created_at?->format('d/m/Y H:i:s')}}</td><td><strong>{{$item->plate ?: $item->uuid}}</strong></td><td>{{$item->person?->full_name ?? '-'}}</td><td>{{$item->response_message ?: 'Osinergmin no devolvió un motivo descriptivo.'}}</td><td>{{$item->response_suggestion ?: 'Sin sugerencia'}}</td></tr>@empty<tr><td colspan="5" class="text-center py-4 text-muted">No hay rechazos guardados en el ambiente activo.</td></tr>@endforelse</tbody></table></div></div><div class="card-footer">{{$recentRejections->links()}}</div></div>
<div class="card"><div class="card-header"><h3 class="card-title">Bitácora de los últimos 30 días</h3></div><div class="card-body p-0"><div class="table-responsive"><table class="table table-sm table-striped mb-0"><thead><tr><th>Fecha</th><th>Ambiente</th><th>Etapa</th><th>Estado</th><th>Cliente</th><th>Mensaje</th></tr></thead><tbody>@foreach($logs as $log)<tr><td class="text-nowrap">{{$log->created_at->format('d/m/Y H:i:s')}}</td><td>{{$log->environment}}</td><td>{{$log->stage}}</td><td><span class="badge badge-{{$log->status==='SUCCESS'?'success':($log->status==='ERROR'?'danger':'secondary')}}">{{$log->status}}</span></td><td>{{$log->person?->full_name ?? 'Sistema'}}</td><td>{{$log->safe_message}} @if($log->safe_context)<details class="mt-1"><summary class="text-primary" style="cursor:pointer">Ver respuesta técnica</summary><pre class="small bg-light p-2 mt-1 mb-0" style="white-space:pre-wrap">{{json_encode($log->safe_context, JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)}}</pre></details>@endif</td></tr>@endforeach</tbody></table></div></div><div class="card-footer">{{$logs->links()}}</div></div>
@can('integration.monitor.purge_demo')<div class="card card-outline card-warning"><div class="card-header"><h3 class="card-title">Preparar producción</h3></div><div class="card-body"><p>Elimina exclusivamente clientes marcados como demo, retransmisiones development y su bitácora. Los datos productivos no se tocan.</p><form method="POST" action="{{route('integration-monitor.purge-demo')}}" onsubmit="return confirm('¿Confirmas la eliminación de todos los datos demo?')">@csrf @method('DELETE')<div class="input-group" style="max-width:480px"><input name="confirmation" class="form-control" placeholder="Escribe ELIMINAR DEMO"><div class="input-group-append"><button class="btn btn-danger"><i class="fas fa-trash mr-1"></i>Limpiar datos demo</button></div></div>@error('confirmation')<small class="text-danger">{{$message}}</small>@enderror</form></div></div>@endcan
@stop
@section('js')<script>
const monitorSections=['Errores por ejecución','Motivos de rechazo por unidad','Bitácora de los últimos 30 días'];
const findMonitorCard=(root,title)=>Array.from(root.querySelectorAll('.card-title')).find(node=>node.textContent.trim()===title)?.closest('.card');
const translateMonitor=()=>{const stages={RUN:'EJECUCIÓN',OCSA:'OCSA',OSINERGMIN:'OSINERGMIN',NETWORK:'RED',WAF:'FIREWALL',PROCESS:'PROCESO',CONFIG:'CONFIGURACIÓN'},states={SUCCESS:'CORRECTO',ERROR:'ERROR',STARTED:'INICIADO',SKIPPED:'OMITIDO',WARNING:'ADVERTENCIA',UNKNOWN:'SIN CONFIRMACIÓN'},environments={production:'Producción',development:'Demo'};const errors=findMonitorCard(document,'Errores por ejecución');errors?.querySelectorAll('tbody tr').forEach(row=>{const cell=row.cells[1];if(cell){const badge=cell.querySelector('.badge');if(badge)badge.textContent=stages[badge.textContent.trim()]||badge.textContent}});const logs=findMonitorCard(document,'Bitácora de los últimos 30 días');logs?.querySelectorAll('tbody tr').forEach(row=>{if(row.cells[1])row.cells[1].textContent=environments[row.cells[1].textContent.trim()]||row.cells[1].textContent;if(row.cells[2])row.cells[2].textContent=stages[row.cells[2].textContent.trim()]||row.cells[2].textContent;const badge=row.cells[3]?.querySelector('.badge');if(badge)badge.textContent=states[badge.textContent.trim()]||badge.textContent});};
const loadMonitorSections=(url,onlyTitle=null,updateUrl=false)=>fetch(url,{headers:{'X-Requested-With':'XMLHttpRequest',Accept:'text/html'}})
 .then(response=>response.ok?response.text():Promise.reject())
 .then(html=>{const documentNew=new DOMParser().parseFromString(html,'text/html');(onlyTitle?[onlyTitle]:monitorSections).forEach(title=>{const current=findMonitorCard(document,title),fresh=findMonitorCard(documentNew,title);if(current&&fresh)current.replaceWith(fresh)});translateMonitor();if(updateUrl)history.pushState({},'',url)})
 .catch(()=>{});
document.addEventListener('click',event=>{const link=event.target.closest('.card-footer .pagination a');if(!link)return;const card=link.closest('.card'),title=card?.querySelector('.card-title')?.textContent.trim();if(!monitorSections.includes(title))return;event.preventDefault();card.style.opacity='.55';loadMonitorSections(link.href,title,true).finally(()=>{if(document.contains(card))card.style.opacity=''})});
window.addEventListener('popstate',()=>loadMonitorSections(location.href));
translateMonitor();
const monitorTimer=setInterval(()=>{if(!document.hidden&&!document.querySelector('details[open]')&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))loadMonitorSections(location.href)},60000);
window.addEventListener('beforeunload',()=>clearInterval(monitorTimer));
</script>@stop
