<!doctype html>
<html lang="es">
<head>
 <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Estado de integración OCSA</title>
 <style>*{box-sizing:border-box}body{font-family:system-ui,-apple-system,sans-serif;background:#f3f7fb;color:#203040;margin:0}.wrap{max-width:1180px;margin:32px auto;padding:0 18px}.head,.card{background:#fff;border-radius:16px;box-shadow:0 8px 28px #16324f12;padding:24px;margin-bottom:20px}.head-top,.summary{display:flex;gap:14px;align-items:center;justify-content:space-between;flex-wrap:wrap}h1,h2{margin:0 0 8px}.state,.badge{display:inline-block;padding:6px 11px;border-radius:20px;font-size:13px;font-weight:800}.state.ok,.badge.ok{background:#d7f5e3;color:#126b35}.state.error,.badge.error{background:#ffe0e3;color:#a7182b}.badge.unknown{background:#fff0c2;color:#795600}.metric{flex:1;min-width:160px;background:#f6f9fc;border:1px solid #e6edf4;border-radius:12px;padding:14px}.metric strong{display:block;font-size:24px}.metric span,.muted{color:#6b7885;font-size:14px}.table{overflow:auto}table{width:100%;border-collapse:collapse}th,td{padding:12px;border-bottom:1px solid #e8eef4;text-align:left;vertical-align:top}th{font-size:13px;color:#526171;background:#f8fafc;position:sticky;top:0}.date{white-space:nowrap}.reason{min-width:260px;max-width:480px}.plate{font-weight:800}.legend{padding:12px 14px;border-left:4px solid #2f80ed;background:#eef6ff;border-radius:8px;margin:14px 0}@media(max-width:700px){.wrap{margin:15px auto}.head,.card{padding:17px}th,td{padding:9px}.optional{display:none}}</style>
</head>
<body><main class="wrap">
 <section class="head">
  <div class="head-top"><div><h1>Estado de retransmisión GPS</h1><p class="muted">Consulta de solo lectura · últimos 30 días · actualizado al recargar</p></div><span class="state {{ $latestRun?->status === 'SUCCESS' ? 'ok' : 'error' }}">{{ $latestRun?->status === 'SUCCESS' ? 'OPERATIVO' : 'CON ERRORES' }}</span></div>
  <p><strong>Última ejecución:</strong> {{ $latestRun?->created_at?->format('d/m/Y H:i:s') ?? 'No disponible' }}</p><p class="muted">{{ $latestRun?->message ?? 'Todavía no existe una ejecución registrada.' }}</p>
  <div class="summary"><div class="metric"><strong>{{ $summary['total'] }}</strong><span>Unidades con actividad</span></div><div class="metric"><strong style="color:#168443">{{ $summary['success'] }}</strong><span>Último envío aceptado</span></div><div class="metric"><strong style="color:#c6283e">{{ $summary['error'] }}</strong><span>Último envío rechazado</span></div><div class="metric"><strong style="color:#946200">{{ $summary['unknown'] }}</strong><span>Respuesta no concluyente</span></div></div>
 </section>
 <section class="card"><h2>Último resultado por unidad</h2><p class="muted">Ordenado desde el envío más reciente. No expone coordenadas, tokens ni nombres de clientes.</p><div class="legend">“Rechazado” significa que Osinergmin respondió, pero no aceptó la trama. El motivo mostrado es el texto devuelto por su API.</div>
  <div class="table"><table><thead><tr><th>Fecha de envío</th><th>Placa</th><th>Resultado</th><th>Motivo / respuesta</th><th class="optional">Sugerencia</th></tr></thead><tbody>
  @forelse($units as $unit) @php($accepted = $unit->response_status === 'SUCCESS') @php($rejected = $unit->response_status === 'ERROR')
   <tr><td class="date">{{ $unit->created_at?->format('d/m/Y H:i:s') }}</td><td class="plate">{{ $unit->plate ?: $unit->uuid }}</td><td><span class="badge {{ $accepted ? 'ok':($rejected?'error':'unknown') }}">{{ $accepted ? 'ACEPTADO':($rejected?'RECHAZADO':'NO CONCLUYENTE') }}</span></td><td class="reason">{{ $unit->response_message ?: ($accepted ? 'Trama recibida correctamente.' : 'La respuesta no incluyó un mensaje descriptivo.') }}</td><td class="optional">{{ $unit->response_suggestion ?: '-' }}</td></tr>
  @empty <tr><td colspan="5">No hay retransmisiones registradas durante los últimos 30 días.</td></tr> @endforelse
  </tbody></table></div>
 </section>
</main></body></html>
